services:
  postgres:
    image: postgres:16-alpine
    container_name: ems-postgres
    environment:
      POSTGRES_DB: ems_db
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: ems_password
    ports:
      - "5432:5432"
    volumes:
      - ems_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user -d ems_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ems_postgres_data:
