spring:
  application:
    name: employee-department-management

  datasource:
    url: jdbc:postgresql://localhost:5432/ems_db
    username: ems_user
    password: ems_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.learning.employeedept: DEBUG
    org.springframework.security: INFO

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
